"""
BUTTON_TEXTS – Словарь, содержащий текстовые метки для кнопок интерфейса у клинента в боте.
"prices": "💰 Цены на услуги",  
"trial": "🎁 Пробный период (3 дня)", и т.д
"""
BUTTON_TEXTS = {
    "share_bot": "Поделиться ботом 🔗",
    "promocode": "🎟️ Промокод ",
    "previous": "🏠 Назад",
    "main_menu": "🏠 Назад",
    "buy_vpn": "💳 Приобрести подписку",
    "cabinet": "🔐 Личный кабинет",
    "prices": "💰 Цены на услуги",
    "referal": "⚡️Реферальная программа",
    "about_server": "⭐️ О нас",
    "setings_router": "VPN для роутера",
    "advantages": "Чем лучше наш VPN?",
    "setting_vpn": "Настроить VPN",
    "support": "🆘 Помощь",
    "extend_subscription_subscr": "🔑 Продлить подписку",
    "extend_subscription": "🔄 Продлить подписку",
    "subscriptions": "🤖 Управление подпиской",
    "change_location": "🌍 Смена локации",
    "instructions": "ℹ️ Инструкции",
    "random": "🎲 Рандом",
    "trial": "🆓 Пробные 3 дня",
    "trial_mes": "🆓 Пробные 30 дней",
    "cancel": "❌ Отмена",
    "pay": "💳 Оплатить",
    "check_pay": "Проверить оплату",
    "without_mail": "Продолжить без ввода 📧email",
    "yokassa": "💳 Оплатить (юкасса)",
    "robokassa": "💰 Робокасса",
    "cryptobot": "💵 CryptoBot",
    "tgpay" : "💳 Telegram Pay",
    "star" : "🌟 Звезды",
    "cloudpay": "💳 CloudPayments",
    "yoomoney": "💳 Юмани",
    "one_m": "🔑 30 дней - 80 рублей",
    "three_m": "🔑 90 дней - 200 рублей",
    "six_m": "📅 6 месяцев",
    "twelve_m": "🔑 365 дней - 750 рублей",
    "ios" : "📱iPhone",
    "android": "🤖 Android",
    "macos": "💻 MacOS",
    "windows": "🖥 Windows",
    "linux": "🐧 Linux",
    "sub": "👉 Наш канал",
    "check_sub": "✅ Проверить подписку",
    "key": "🔑 Получить ключ",
    "test": "test",
    "trial_seven": "7 дней бесплатно",
}